### ISSUE TITLE
Reduce baud rate when Enhanced CH34x detected

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun_RTK_Firmware_Uploader#4]
![image](https://github.com/sparkfun/SparkFun_RTK_Firmware_Uploader/assets/117102/76278dfc-1216-45a2-afbe-14b5e2998b05)

On some hardware platforms, the ESP32 is behind the CH342 which seems to not like 921600bps. Would it make sense to auto limit the baud to 460800 (works) or 512000 (would need to be added)? This may save some production folks some confusion.

**Comment by PaulZC** [comment]
Resolved in https://github.com/sparkfun/SparkFun_RTK_Firmware_Uploader/releases/tag/v1.6.1
